require_relative "chess/board"
require_relative "chess/move"
require_relative "chess/piece"
require_relative "chess/piece_factory"
require_relative "chess/pieces/rook"
require_relative "chess/pieces/bishop"
require_relative "chess/pieces/knight"
require_relative "chess/pieces/queen"
require_relative "chess/pieces/king"
require_relative "chess/pieces/pawn"

